mybatis-plus:

    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.demo.dao

spring:
    datasource:

        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/boot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        initial-size: 5
        min-idle: 5
        max-active: 20
